# Funding links shown as a "Sponsor" button on this repository.
# Only takes effect from the default branch.
github: shrimpwagon
ko_fi: canebaycomputers
patreon: canebaycomputers
custom: ["https://securelink-prod.valorpaytech.com:4430/?redirect=1&uid=6e840752-8751-11f0-a74f-12a0879a85b1"]
