#!/bin/bash

# Regenerate src/catalog/apps.json from the installers in src/installers/.
#
# The app half of the catalogue is GENERATED, not hand-written: a hand-typed
# table of 100 forced databases would rot the first time an installer changed
# engines and nobody updated the table. Each installer already states its
# database in the compose it writes, so we read it back from the source of
# truth instead.
#
# Run after adding, removing or re-pointing an installer:
#     bash src/scripts/build_catalog.sh
#
# `podium create` warns when the installer count and the catalogue disagree.

set -e

cd "$(cd "$(dirname "$0")" 2>/dev/null && pwd -P)"
cd ..
DEV_DIR=$(pwd)

INSTALLER_DIR="$DEV_DIR/installers"
OUT="$DEV_DIR/catalog/apps.json"

mkdir -p "$DEV_DIR/catalog"

python3 - "$INSTALLER_DIR" "$OUT" << 'PYEOF'
import json, os, re, sys

installer_dir, out = sys.argv[1], sys.argv[2]

# Order matters: a compose naming both podium-postgres and podium-redis is a
# postgres app with a redis cache, so cache engines are never treated as "the"
# database. Redis/memcached are deliberately absent from this map.
ENGINES = [
    (re.compile(r'podium-postgres', re.I), "postgres"),
    (re.compile(r'podium-mariadb',  re.I), "mysql"),
    (re.compile(r'podium-mongo',    re.I), "mongodb"),
    (re.compile(r'sqlite',          re.I), "sqlite"),
]

apps = []
for fn in sorted(os.listdir(installer_dir)):
    if not fn.endswith(".sh"):
        continue
    slug = fn[:-3]
    raw = open(os.path.join(installer_dir, fn), encoding="utf-8", errors="replace").read()

    m = re.search(r'^INSTALL_DISPLAY="([^"]*)"', raw, re.M)
    display = m.group(1) if m else slug

    m = re.search(r'^INSTALL_NOTES="([^"]*)"', raw, re.M)
    note = (m.group(1) if m else "").strip()

    found = [name for pat, name in ENGINES if pat.search(raw)]
    # First match wins; a server engine always outranks a bundled sqlite file.
    database = found[0] if found else ""

    entry = {"slug": slug, "display": display, "database": database}
    if note:
        entry["note"] = note
    apps.append(entry)

doc = {
    "_comment": ("GENERATED by src/scripts/build_catalog.sh — do not edit by hand. "
                 "'database' is what the installer's compose actually wires up; it is fixed "
                 "by the installer, so `podium create` never asks the user to choose one for "
                 "an app. Empty means the app manages its own storage internally."),
    "apps": apps,
}
with open(out, "w", encoding="utf-8") as f:
    json.dump(doc, f, indent=2)
    f.write("\n")

by_engine = {}
for a in apps:
    by_engine[a["database"] or "(internal)"] = by_engine.get(a["database"] or "(internal)", 0) + 1
print(f"wrote {len(apps)} apps to {out}")
print("  " + "  ".join(f"{k}={v}" for k, v in sorted(by_engine.items())))
PYEOF
