services:
  server:
    image: canebaycomputers/cbc:nginx-node
    container_name: CONTAINER_NAME
    environment:
      - "NODE_APP_COMMAND=NODE_START_COMMAND"
    ports:
      - "PROJECT_PORT:80"
    volumes:
      - .:/usr/share/nginx/html
      - /etc/hosts:/etc/hosts:ro
    networks:
      default:
        ipv4_address: IPV4_ADDRESS

networks:
  default:
    external: true
    name: podium-cli_vpc
